# Generated by Django 2.2.6 on 2019-11-05 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="level",),
        migrations.RemoveField(model_name="category", name="lft",),
        migrations.RemoveField(model_name="category", name="rght",),
        migrations.RemoveField(model_name="category", name="tree_id",),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="categories.Category",
            ),
        ),
    ]
